[package]
name = "rust_os"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = "0.11.2"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }

[dependencies]
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = ["kernel", "tinypci"]
